name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build
        env:
          GRADLE_TOS_AGREE: yes

      - name: List files for debugging
        run: find . -type f -print
      
      - name: Upload Fabric Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fabric-artifacts
          path: build/libs/*.jar

#      - name: Deploy
#        if: startsWith(github.ref, 'refs/tags/v')
#        run: 'curl --fail -X POST -H "Authorization: Bearer ${{ secrets.DEPLOY }}" -F "upload=@$(ls -1 build/libs/merged/*.jar)" https://api.mrmelon54.com/v1/mc-upload/upload/armored-elytra'
